name: Java CI CD

on: [push,pull_request] # 触发事件

jobs:
  bt-product-realease:
    if: ${{ github.ref == 'refs/heads/main' }} # 检测main分支是否有更新
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3 # pull代码到服务器上

      #- name: Set up Docker buildx
        #uses: docker/setup-buildx-action@v1
        
      #- name: Login to private container registry
        #uses: docker/login-action@v1 # 使用阿里云镜像服务action
        #with:
          #server: ${{ secrets.DOCKER_REGISTRY }} # registry.cn-hangzhou.aliyuncs.com # 容器镜像服务地址
          #username: "${{ secrets.REGISTRY_USERNAME }}"  # 引用GitHub repo设置的镜像容器服务用户名
          #password: "${{ secrets.REGISTRY_PASSWORD }}"  # 引用GitHub repo设置的镜像容器服务密码
      
      - name: Login to Aliyun Container Registry(ACR)
        uses: aliyun/acr-login@v1 # 使用阿里云镜像服务action
        with:
          login-server: "${{ secrets.DOCKER_REGISTRY }}" # 容器镜像服务地址
          region-id: cn-hangzhou
          username: "${{ secrets.REGISTRY_USERNAME }}"  # 引用GitHub repo设置的镜像容器服务用户名
          password: "${{ secrets.REGISTRY_PASSWORD }}"  # 引用GitHub repo设置的镜像容器服务密码
          
      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha}} # 用于标记容器版本号
        run:
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/lintao_public/app:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_REGISTRY }}/lintao_public/app:$IMAGE_TAG
          
